name: 'The name of your action here'
description: 'Provide a description here'
author: 'Your name or organization here'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  ak:
    description: 'Access Key ID'
    required: true

  sk:
    description: 'Secret Access Key'
    required: true

  ns:
    description: 'namespace'
    required: true

  region:
    description: 'SWR Region'
    required: true

  repository:
    description: 'Image repository'
    required: true

  tag:
    description: 'Image version'
    required: true

  project_id:
    description: 'huaweicloud project_id'
    required: false
    default: ''

runs:
  using: node20
  main: dist/index.js
